bind -n M-l next-window

bind -n M-h previous-window

bind -n M-q new-window

bind -n M-d kill-window

set -g status-style bg="#0097d5"

set -g status-style fg="black",bg="#00a9ee"

set -g base-index 1
setw -g pane-base-index 1

set -g renumber-windows on

set-option -g status-position bottom
