include ./mocha.conf font_family jetbrains mono nerd font
font_size 11
bold_font auto
italic_font auto
bold_italic_font auto
mouse_hide_wait 2.0
cursor_shape block
enabled_layouts splits

# Allow other apps to control kitty: for neovim dynamic padding
allow_remote_control yes
listen_on unix:/tmp/mykitty

#Close the terminal without confirmation
confirm_os_window_close 0

url_color #0087bd
url_style dotted
background_opacity 0.6
foreground #00d9ee
color1 #ff5c57
color3 #f3f99d
color2 #5af78e
color4 #57c7ff

########## KEY BINDINGS ##########
map alt+l next_tab
map alt+h previous_tab

map alt+q new_tab
map alt+d close_tab
map alt+d close_window

map alt+shift+h neighboring_window left
map alt+shift+l neighboring_window right
map alt+shift+k neighboring_window up
map alt+shift+j neighboring_window down

# Open new split to the right (Vertical)
map alt+shift+q launch --location=vsplit --cwd=current
# Open new split below (Horizontal)
map alt+shift+w launch --location=hsplit --cwd=current


########## WINDOW BORDERS ##########
window_border_width 1pt
active_border_color #00a9ee
inactive_border_color #595959
window_padding_width 20



